plugins {
    id 'com.android.application'
}

android {
    namespace 'com.openwrt.luci'
    compileSdk 34

    defaultConfig {
        applicationId "com.openwrt.luci"
        minSdk 21
        targetSdk 34
        versionCode 16
        versionName "2.5"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

// Murni tanpa dependensi pihak ketiga (WebView = framework Android)
